version: '3'

tasks:
  default:
    desc: List all available tasks
    cmds:
      - task --list

  build:
    desc: Build all executables (todo, tododiff, todopatch, etc.)
    deps:
      - build:todo
      - build:tododiff
      - build:todopatch
    cmds: []

  build:todo:
    desc: Build the todo executable
    cmds:
      - mkdir -p bin
      - go build -o bin/todo ./cmd/todo

  build:todopatch:
    desc: Build the todopatch executable
    cmds:
      - mkdir -p bin
      - go build -o bin/todopatch ./cmd/todopatch

  build:tododiff:
    desc: Build the tododiff executable
    cmds:
      - mkdir -p bin
      - go build -o bin/tododiff ./cmd/tododiff

  run:
    desc: Run the todo application
    cmds:
      - go run ./cmd/todo

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
